### ISSUE TITLE
Notebooks should use the util file

### ISSUE THREAD

**Issue by jbe456** [atoti/notebooks#10]
The utils file is not used yet.

Instead the `download_source` function is duplicated inside the Collateral shortfall monitoring notebook:
![image](https://user-images.githubusercontent.com/4415696/79256517-71e97a00-7e88-11ea-9781-e78114244815.png)

And is not used inside Pricing simulations around product classes.

We should instead factorize the code to leverage the utils function.

**Comment by HuifangYeo** [comment]
https://github.com/atoti/notebooks/pull/15
