### ISSUE TITLE
AttributeError: 'spacy.tokens.token.Token' object has no attribute 'string'

### ISSUE THREAD

**Issue by LaKo13** [atoti/notebooks#112]
## Notebook

https://github.com/atoti/notebooks/blob/master/notebooks/reddit/main.ipynb
## Steps to reproduce
AttributeError                            Traceback (most recent call last)
<ipython-input-14-2c17d9aad936> in <module>
----> 1 posts = get_latest_posts("wallstreetbets", 500)
      2 entity_file.flush()
      3 
      4 # check the number of posts retrieved
      5 len(posts)

<ipython-input-13-f5e80723cc2c> in get_latest_posts(subreddit, count)
      7     for post in new_bets:
      8         # normalize the post and perform NLP named entities extraction
----> 9         lemmatized_post = normalize("post", post.id, post.selftext)
     10         lemmatized_title = normalize("title", post.id, post.title)
     11         _posts.append(

<ipython-input-10-748bd76451b7> in normalize(category, id, post)
     15 
     16     complete_filtered_tokens = [
---> 17         preprocess_token(token) for token in nlp_text if is_token_allowed(token)
     18     ]
     19 

<ipython-input-10-748bd76451b7> in <listcomp>(.0)
     15 
     16     complete_filtered_tokens = [
---> 17         preprocess_token(token) for token in nlp_text if is_token_allowed(token)
     18     ]
     19 

<ipython-input-10-748bd76451b7> in is_token_allowed(token)
      1 # https://realpython.com/natural-language-processing-spacy-python/
      2 def is_token_allowed(token):
----> 3     if not token or not token.string.strip() or token.is_stop or token.is_punct:
      4         return False
      5     return True

AttributeError: 'spacy.tokens.token.Token' object has no attribute 'string'
## Actual Result
None

## Expected Result
len(posts)
## Environment
Python Anaconda Virtual Environment -v 3.7.7

- Python: 3.7.7
- Operating System: MAC

**Comment by HuifangYeo** [comment]
Hi @LaKo13,

Apologies for the late reply. I have fixed the issue and it's merged to master.

Cheers,
