### ISSUE TITLE
Remaining notebooks to migrate to version 0.6.0

### ISSUE THREAD

**Issue by Skyscimitar** [atoti/notebooks#187]
Some notebooks have yet to be updated to version 0.6.0.

- [x] [customer-churn](https://github.com/atoti/notebooks/blob/master/notebooks/customer-churn/main.ipynb)
- [x] [formula-one](https://github.com/atoti/notebooks/blob/master/notebooks/formula-one/main.ipynb)
- [x] [pricing-simulations-around-product-classes](https://github.com/atoti/notebooks/blob/master/notebooks/pricing-simulations-around-product-classes/main.ipynb)
- [x] [rollup-hierarchies](https://github.com/atoti/notebooks/blob/master/notebooks/rollup-hierarchies/main.ipynb)
- [x] [topcount](https://github.com/atoti/notebooks/blob/master/notebooks/topcount/atoti.ipynb)
- [x] [twitter](https://github.com/atoti/notebooks/blob/master/notebooks/twitter/main.ipynb)
- [x] [value-at-risk](https://github.com/atoti/notebooks/blob/master/notebooks/value-at-risk/main.ipynb)
- [x] [var-benchmark](https://github.com/atoti/notebooks/blob/master/notebooks/var-benchmark/main.ipynb)
- [x] [var-impact-in-premier-league](https://github.com/atoti/notebooks/blob/master/notebooks/var-impact-in-premier-league/main.ipynb)
- [x] [reddit](https://github.com/atoti/notebooks/tree/master/notebooks/reddit/main.ipynb)

For now I've removed them from the tests so that the CI can run without problems.
As these notebooks are updated, don't forget to remove them from the `NOTEBOOKS_TO_BE_UPDATED` list in [execute_notebooks.py](https://github.com/atoti/notebooks/blob/master/tests/execute_notebooks.py).

**Comment by HuifangYeo** [comment]
Upgrade completed with https://github.com/atoti/notebooks/pull/243
