### ISSUE TITLE
Pnl explained yield curve

### ISSUE THREAD

**Issue by jbe456** [atoti/notebooks#19]
![image](https://user-images.githubusercontent.com/4415696/81019620-54944400-8e67-11ea-8765-afc975ca5a84.png)

- I fixed the X axis and Y axis labels inverted in https://github.com/atoti/notebooks/pull/20
- do we need to split by currency rather than filtering on one currency if it's the same?
- do we need to show both start and end of day?

**Comment by HuifangYeo** [comment]
- Indeed we can focus on just EUR instead. 
- I don't really think we need to show both start and end of day but I kept it as per what Imad has done.

I'll update the changes.
