### ISSUE TITLE
Fail to run credit card fraud detection

### ISSUE THREAD

**Issue by bloussou** [atoti/notebooks#300]
This notebook is really hard to run. 

A lot of dependencies are missing in the pyproject.toml. Can you please add these dependencies ?

I'm running it on a really good computer and I get the following issue :
![image](https://user-images.githubusercontent.com/32448554/142659044-c4ab11e9-4e95-45c6-ba26-59d0ad23bc67.png)

**Comment by HuifangYeo** [comment]
Hi @bloussou,

the testing issues have been fixed and merged.

**Comment by HuifangYeo** [comment]
I've excluded the notebook from testing as there are conflicts between the dependencies of pycaret and atoti.
