### ISSUE TITLE
Churn prediction

### ISSUE THREAD

**Issue by jbe456** [atoti/notebooks#40]
## Description

Customers Churn prediction:

>Customer attrition, also known as customer churn, customer turnover, or customer defection, is the loss of clients or customers.
>
>Telephone service companies, Internet service providers, pay TV companies, insurance firms, and alarm monitoring services, often use customer attrition analysis and customer attrition rates as one of their key business metrics because the cost of retaining an existing customer is far less than acquiring a new one. Companies from these sectors often have customer service branches which attempt to win back defecting clients, because recovered long-term customers can be worth much more to a company than newly recruited clients.
>
>Companies usually make a distinction between voluntary churn and involuntary churn. Voluntary churn occurs due to a decision by the customer to switch to another company or service provider, involuntary churn occurs due to circumstances such as a customer's relocation to a long-term care facility, death, or the relocation to a distant location. In most applications, involuntary reasons for churn are excluded from the analytical models. Analysts tend to concentrate on voluntary churn, because it typically occurs due to factors of the company-customer relationship which companies control, such as how billing interactions are handled or how after-sales help is provided.
>
>predictive analytics use churn prediction models that predict customer churn by assessing their propensity of risk to churn. Since these models generate a small prioritized list of potential defectors, they are effective at focusing customer retention marketing programs on the subset of the customer base who are most vulnerable to churn.

Possible steps:
>- Identify and visualize which factors contribute to customer churn:
>- Build a prediction model that will perform the following:
>    - Classify if a customer is going to churn or not
>    - Preferably and based on model performance, choose a model that will attach a probability to the churn to make it easier for customer service to target low hanging fruits in their efforts to prevent churn

## Resources

- https://www.kaggle.com/pavanraj159/telecom-customer-churn-prediction
- https://www.kaggle.com/kmalit/bank-customer-churn-prediction

**Comment by HuifangYeo** [comment]
Implemented [Telco Churn](https://github.com/atoti/notebooks/tree/master/Communications/customer-churn)

**Comment by jbe456** [comment]
Closed by https://github.com/atoti/notebooks/pull/52
